# probot-stale 설정 - https://github.com/probot/stale

# 이슈나 풀 리퀘스트가 오래된 상태로 표시되기까지의 비활성 일수
daysUntilStale: 30

# 오래된 라벨이 붙은 이슈나 풀 리퀘스트가 닫히기까지의 비활성 일수
# false로 설정하면 비활성화됩니다. 비활성화된 경우 이슈는 여전히 수동으로 닫아야 하지만 오래된 상태로 표시됩니다.
daysUntilClose: 5

# 오래된 상태 확인 시 이 라벨이 모두 있는 이슈나 풀 리퀘스트만 확인합니다. 기본값은 `[]` (비활성화)
onlyLabels: []

# 이 라벨이 있는 이슈나 풀 리퀘스트는 절대 오래된 상태로 간주되지 않습니다. 비활성화하려면 `[]`로 설정
exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"

# 프로젝트 내 이슈를 무시하려면 true로 설정 (기본값은 false)
exemptProjects: false

# 마일스톤 내 이슈를 무시하려면 true로 설정 (기본값은 false)
exemptMilestones: false

# 담당자가 있는 이슈를 무시하려면 true로 설정 (기본값은 false)
exemptAssignees: false

# 오래된 상태로 표시할 때 사용할 라벨
staleLabel: stale

# 오래된 상태로 표시할 때 게시할 댓글. 비활성화하려면 `false`로 설정
markComment: >

# 시간당 작업 수를 1-30 사이로 제한합니다. 기본값은 30
limitPerRun: 30

# 선택적으로 '이슈'나 '풀 리퀘스트'에만 특정한 설정을 지정할 수 있습니다:
pulls:
  markComment: >
    기여해 주셔서 감사합니다! 하지만 지난 30일 동안 
    활동이 없었으며, 5일 내에 업데이트가 없으면 닫힐 예정입니다. 
    변경 사항이 여전히 유효하다고 생각하시면 브랜치가 대상 브랜치와 
    충돌이 없는지 확인하고 필요한 경우 리베이스하세요. 
    (재)검토를 기다리고 계시다면 알려주세요.

issues:
  markComment: >
    기여해 주셔서 감사합니다! 하지만 지난 30일 동안 
    활동이 없었으며, 5일 내에 업데이트가 없으면 닫힐 예정입니다. 
    이 이슈를 계속 열어두고 싶으시다면:

      1. 최신 버전의 service-desk에서도 이슈를 재현할 수 있는지 확인하세요
      1. 이슈가 여전히 재현 가능하다는 댓글을 남기고 다음 내용을 포함하세요:
          * 어떤 버전의 service-desk에서 이슈를 재현했는지
          * 어떤 OS 및 버전에서 이슈를 재현했는지
          * 이슈를 재현하기 위해 어떤 단계를 따랐는지
#   exemptLabels:
#     - confirmed
