name: POS UI CI

on:
  push:
    branches:
      - dev
      - master
      - rc
      - v1
    paths:
      - 'pos/**'
      - '.github/workflows/pos-ui.yaml'

  pull_request:
    branches:
      - dev
      - master
      - rc
      - v1
    paths:
      - 'pos/**'
      - '.github/workflows/pos-ui.yaml'

jobs: 
  pos-ui:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.18.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'yarn'

      # Yarn classic 고정
      - name: Enable Yarn classic
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd pos
          yarn install --frozen-lockfile --network-timeout 600000
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        run: |
          cd pos
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build -t 5240help/pos-ui:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push 5240help/pos-ui:${GITHUB_REF#refs/heads/}
